### ISSUE TITLE
Should Phasor be re-named?

### ISSUE THREAD

**Issue by nwolek** [jamoma/jamoma2#64]
https://github.com/jamoma/jamoma2/blob/master/includes/library/JamomaPhasor.h

I realize the name is borrowed from MSP, but for the non-Max user there is potential confusion with these (some more serious than others):

https://en.wikipedia.org/wiki/Phasor
https://en.wikipedia.org/wiki/Phaser_(effect)
https://en.wikipedia.org/wiki/Weapons_in_Star_Trek#Phaser
https://en.wikipedia.org/wiki/Phasor_(sound_synthesizer)

The only option I can think of is PhaseRamp, which is boring but better than NonbandlimitedSawtooth.

**Comment by tap** [comment]
Indeed.  There are a number of "Saw" UGens in SuperCollider.  http://doc.sccode.org/Browse.html#UGens%3EGenerators%3EDeterministic

I'm not sold on LFSaw though.

I propose something like `Sync`.  Because really that's what we are trying to achieve when using this oscillator to generate a phase signal.

**Comment by nwolek** [comment]
Sync is good. I'll make this change today.

**Comment by nwolek** [comment]
@tap - I have this finished in a local branch. Setting up as a pull request since the folder renaming with require you to run the CMake builds.
